"""Render MaintainerSummary to Markdown and JSON output files."""

from __future__ import annotations

import json
import logging
from pathlib import Path

from codesteward.schemas import MaintainerSummary, ReviewComment, ReviewerReview

logger = logging.getLogger(__name__)


def render_markdown(summary: MaintainerSummary) -> str:
    """Render the maintainer summary as a human-readable Markdown report."""
    lines: list[str] = []

    # Header
    pr_ref = f"PR #{summary.pr_number}" if summary.pr_number else "Diff"
    lines.append(f"# Review Report: {pr_ref}")
    if summary.pr_title:
        lines.append(f"**{summary.pr_title}**")
    lines.append(f"\nRepository: `{summary.repo}`")
    lines.append(f"Generated: {summary.generated_at.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    # Verdict
    verdict_emoji = {
        "READY": "READY",
        "NEEDS_CHANGES": "NEEDS CHANGES",
        "RISKY": "RISKY",
    }
    lines.append(f"## Merge Verdict: **{verdict_emoji.get(summary.verdict.value, summary.verdict.value)}**")
    lines.append("")

    # Risk flags
    if summary.risk_flags:
        lines.append("### Risk Flags")
        for flag in summary.risk_flags:
            lines.append(f"- `{flag}`")
        lines.append("")

    # Per-reviewer sections
    lines.append("---")
    lines.append("## Reviewer Reports")
    lines.append("")

    for review in summary.reviewer_reviews:
        lines.append(f"### {review.reviewer}")
        lines.append(f"**Verdict:** {review.verdict}")
        lines.append("")

        if review.summary_bullets:
            lines.append("**Summary:**")
            for bullet in review.summary_bullets:
                lines.append(f"- {bullet}")
            lines.append("")

        if review.comments:
            _render_comment_section(lines, "Blockers", [c for c in review.comments if c.kind == "blocker"])
            _render_comment_section(lines, "Missing Tests", [c for c in review.comments if c.kind == "missing-test"])
            _render_comment_section(lines, "Suggestions", [c for c in review.comments if c.kind == "suggestion"])
            _render_comment_section(lines, "Docs Needed", [c for c in review.comments if c.kind == "docs-needed"])
            _render_comment_section(lines, "Questions", [c for c in review.comments if c.kind == "question"])

        lines.append("")

    # Consolidated blockers
    if summary.merged_blockers:
        lines.append("---")
        lines.append("## Consolidated Blockers")
        lines.append("")
        for i, b in enumerate(summary.merged_blockers, 1):
            file_ref = f" (`{b.file}`" + (f":{b.line}" if b.line else "") + ")" if b.file else ""
            lines.append(f"{i}. **{b.body}**{file_ref}")
            if b.evidence:
                lines.append(f"   - Evidence [{b.evidence.type.value}]: `{b.evidence.ref}`")
                if b.evidence.snippet:
                    lines.append(f"   - `{b.evidence.snippet[:100]}`")
        lines.append("")

    # Disagreements
    if summary.disagreements:
        lines.append("## Disagreements")
        lines.append("")
        for d in summary.disagreements:
            lines.append(f"- **{d.get('type', 'unknown')}**: {d.get('note', '')}")
        lines.append("")

    # Fix plan
    if summary.fix_plan:
        lines.append("## Prioritized Fix Plan")
        lines.append("")
        for item in summary.fix_plan:
            lines.append(f"- {item}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Reviewer Pattern Agent*")

    return "\n".join(lines)


def render_json(summary: MaintainerSummary) -> str:
    """Render the maintainer summary as structured JSON."""
    return summary.model_dump_json(indent=2)


def write_outputs(summary: MaintainerSummary, output_dir: str = "./out") -> tuple[Path, Path]:
    """Write Markdown and JSON outputs to the output directory."""
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    md_path = out_path / "review.md"
    json_path = out_path / "review.json"

    md_content = render_markdown(summary)
    json_content = render_json(summary)

    md_path.write_text(md_content, encoding="utf-8")
    json_path.write_text(json_content, encoding="utf-8")

    logger.info("Wrote review report to %s", md_path)
    logger.info("Wrote review JSON to %s", json_path)

    return md_path, json_path


def _render_comment_section(lines: list[str], title: str, comments: list[ReviewComment]) -> None:
    """Render a section of comments."""
    if not comments:
        return
    lines.append(f"**{title}:**")
    for c in comments:
        file_ref = ""
        if c.file:
            file_ref = f" `{c.file}"
            if c.line:
                file_ref += f":{c.line}"
            file_ref += "`"
        lines.append(f"- {c.body}{file_ref}")
        if c.evidence:
            lines.append(f"  - *Evidence [{c.evidence.type.value}]*: `{c.evidence.ref}`")
    lines.append("")
